apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'
apply plugin: 'kotlin-kapt'

android {
    namespace 'com.example.chuckfacts'
    compileSdkVersion 37
    // buildToolsVersion "29.0.2"

    buildFeatures {
        buildConfig = true
        resValues = true
        viewBinding = true
        dataBinding = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }

    defaultConfig {
        applicationId "com.example.chuckfacts"
        minSdkVersion 35
        targetSdkVersion 37
        versionCode 2
        versionName "2.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.androidx.legacy.support.v4

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.core.ktx
    implementation libs.androidx.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core

    // Timber library for Logging
    implementation libs.timber
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx

    //Retrofit2
    implementation libs.retrofit
    implementation libs.converter.moshi
    implementation libs.retrofit2.kotlin.coroutines.adapter

    //Moshi
    implementation libs.moshi.kotlin
    kapt libs.moshi.kotlin.codegen

    //Kotlin Coroutines
    implementation libs.kotlinx.coroutines.android
    implementation libs.kotlinx.coroutines.core

    //Room Local DB
    implementation libs.androidx.room.runtime
    implementation libs.androidx.room.ktx
    kapt libs.androidx.room.compiler


}
